import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import {
  BrowserView,
  MobileView,
  isBrowser,
  isMobile,
} from "react-device-detect";
import Dashboard from "../components/Desktop/Dashboard/Dashboard";
import Mobile_Home from "../components/Mobile/Home/Mobile_Home";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MobileView>
          <Mobile_Home />
        </MobileView>
        <BrowserView>
          <Mobile_Home />
        </BrowserView>
      </main>
    </div>
  );
}
